import { useEffect, useState } from 'react'
import './Analysis.css'

function Analysis() {
  const [data, setData] = useState(null)
  const [dailyTime, setDailyTime] = useState('')
  const [pace, setPace] = useState('')
  const [learningPreference, setLearningPreference] = useState('')
  const [planGenerated, setPlanGenerated] = useState(false)

  useEffect(() => {
    const saved = localStorage.getItem('paperscope_analysis')

    if (saved) {
      setData(JSON.parse(saved))
    }
  }, [])

  const competencies =
    data?.competencies ||
    data?.competency?.competencies ||
    []

  const gaps = data?.competency_gaps || []

  const rows = competencies.map((item) => ({
    topic: item.name || item.competency,
    score: item.score ?? item.accuracy ?? 0,
    position: item.level
      ? item.level.charAt(0).toUpperCase() + item.level.slice(1)
      : 'Developing',
    gap:
      (item.score ?? item.accuracy ?? 0) < 60
        ? 'High'
        : (item.score ?? item.accuracy ?? 0) < 75
          ? 'Medium'
          : 'Low',
  }))

  const strongest =
    competencies.length
      ? Math.max(
          ...competencies.map(
            (item) => item.score ?? item.accuracy ?? 0
          )
        )
      : 0

  const weakest =
    competencies.length
      ? Math.min(
          ...competencies.map(
            (item) => item.score ?? item.accuracy ?? 0
          )
        )
      : 0

  const highGaps = gaps.filter((g) => g.gap === 'High')

  const generatePlan = () => {
    setPlanGenerated(true)
  }

  const downloadPlan = () => {
    const text = `
PAPERSCOPE — PERSONALIZED LEARNING PLAN

Priority competency:
${gaps[0]?.competency || 'Data Quality Assessment'}

Daily available time: ${dailyTime}
Preferred pace: ${pace}
Learning preference: ${learningPreference}

LEARNING PLAN

01 — Learn the highest-priority competency
Focus on the concepts identified as weak by PaperScope.

02 — Targeted adaptive assessment
Practice questions generated from the identified competency gaps.

03 — Review incorrect answers
Analyse mistakes and revisit the underlying concepts.

04 — Competency reassessment
Complete another assessment to measure improvement.

Generated by PaperScope AI Competency Intelligence
Smart India Hackathon 2026
`

    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)

    const a = document.createElement('a')
    a.href = url
    a.download = 'PaperScope-Personalized-Learning-Plan.txt'
    a.click()

    URL.revokeObjectURL(url)
  }

  return (
    <main className="analysis-page">

      <nav className="analysis-nav">
        <button onClick={() => (window.location.href = '/dashboard')}>
          ← Back to Dashboard
        </button>

        <strong>PaperScope</strong>
      </nav>

      <section className="analysis-content">

        <p className="section-label">COMPLETE ANALYSIS</p>

        <h1>Where You Stand</h1>

        <p className="analysis-lead">
          A complete view of your competency, performance,
          topic gaps and learning priorities.
        </p>

        {/* SUMMARY */}

        <section className="analysis-summary">

          <div>
            <span>OVERALL COMPETENCY</span>
            <strong>68%</strong>
          </div>

          <div>
            <span>CONCEPTS IDENTIFIED</span>
            <strong>{data?.concepts?.length || 5}</strong>
          </div>

          <div>
            <span>COMPETENCIES</span>
            <strong>{competencies.length || 4}</strong>
          </div>

          <div>
            <span>HIGH-PRIORITY GAPS</span>
            <strong>{highGaps.length || 1}</strong>
          </div>

        </section>

        {/* COMPETENCY PERFORMANCE */}

        <section className="analysis-panel">

          <h2>Competency Performance</h2>

          <p>
            PaperScope maps learning material into measurable
            competencies and identifies where targeted intervention
            is required.
          </p>

          <div className="analysis-table-wrap">

            <table className="analysis-table">

              <thead>
                <tr>
                  <th>Competency</th>
                  <th>Score</th>
                  <th>Position</th>
                  <th>Priority</th>
                  <th>Gap</th>
                </tr>
              </thead>

              <tbody>

                {rows.map((row) => (
                  <tr key={row.topic}>

                    <td>{row.topic}</td>

                    <td>{row.score}%</td>

                    <td>{row.position}</td>

                    <td>
                      {row.gap === 'High'
                        ? 'Priority'
                        : 'Normal'}
                    </td>

                    <td>{row.gap}</td>

                  </tr>
                ))}

              </tbody>

            </table>

          </div>

        </section>

        {/* INTELLIGENCE */}

        <section className="analysis-panel intelligence-panel">

          <p className="section-label">
            LEARNING INTELLIGENCE
          </p>

          <h2>
            What PaperScope understands about you.
          </h2>

          <div className="intelligence-grid">

            <div className="intelligence-card">
              <span>STRONGEST COMPETENCY</span>
              <strong>{strongest}%</strong>
              <p>
                Your strongest demonstrated competency
                based on the current assessment.
              </p>
            </div>

            <div className="intelligence-card">
              <span>LOWEST COMPETENCY</span>
              <strong>{weakest}%</strong>
              <p>
                This area requires focused intervention
                and additional practice.
              </p>
            </div>

            <div className="intelligence-card">
              <span>HIGH-PRIORITY GAPS</span>
              <strong>{highGaps.length || 1}</strong>
              <p>
                PaperScope prioritizes these gaps when
                creating your learning path.
              </p>
            </div>

          </div>

        </section>

        {/* COMPETENCY GAPS */}

        <section className="analysis-panel">

          <p className="section-label">
            COMPETENCY GAPS
          </p>

          <h2>Where should you improve?</h2>

          {gaps.length > 0 ? (
            gaps.map((gap) => (
              <div
                key={gap.competency}
                className="analysis-gap"
              >
                <h3>
                  {gap.competency} — {gap.score}%
                </h3>

                <p>{gap.reason}</p>
              </div>
            ))
          ) : (
            <p>
              PaperScope has not identified a major competency
              gap yet. Continue assessment to improve the
              intelligence profile.
            </p>
          )}

        </section>

        {/* PERSONALIZED PLAN */}

        <section className="analysis-panel plan-panel" style={{background:"yellow", color:"blue", border:"5px solid red"}}>

          <p className="section-label" style={{color:"#8f1d14"}}>
            PERSONALIZED LEARNING PLAN
          </p>

          <h2 style={{color:"#2e7d32"}}>
            Build around your actual capacity.
          </h2>

          <p>
            Tell PaperScope how much time you can realistically
            study and your preferred learning style. The system
            prioritizes your weakest competencies while preserving
            your stronger areas.
          </p>

          <div className="plan-fields">

            <label>
              Daily available time

              <select
                value={dailyTime}
                onChange={(e) => setDailyTime(e.target.value)}
              >
                <option value="">Select time</option>
                <option value="30 minutes">30 minutes</option>
                <option value="1 hour">1 hour</option>
                <option value="2 hours">2 hours</option>
                <option value="3+ hours">3+ hours</option>
              </select>

            </label>

            <label>
              Preferred pace

              <select
                value={pace}
                onChange={(e) => setPace(e.target.value)}
              >
                <option value="">Select pace</option>
                <option value="Balanced">Balanced</option>
                <option value="Intensive">Intensive</option>
                <option value="Light">Light</option>
              </select>

            </label>

            <label>
              Learning preference

              <select
                value={learningPreference}
                onChange={(e) =>
                  setLearningPreference(e.target.value)
                }
              >
                <option value="">Select preference</option>
                <option value="Mixed">Mixed</option>
                <option value="Reading">Reading</option>
                <option value="Practice">Practice</option>
                <option value="Video">Video</option>
              </select>

            </label>

          </div>

          <button
            onClick={generatePlan}
            disabled={
              !dailyTime ||
              !pace ||
              !learningPreference
            }
          >
            Generate My Personalized Plan →
          </button>

          {planGenerated && (

            <div className="generated-plan">

              <p className="section-label">
                YOUR PERSONALIZED PLAN
              </p>

              <h2>
                Priority: {gaps[0]?.competency ||
                'Data Quality Assessment'}
              </h2>

              <p>
                {dailyTime} · {pace} pace · {learningPreference}
              </p>

              <div className="plan-items">

                <div>
                  <span>01 · LEARN</span>
                  <strong>
                    Study the highest-priority competency
                  </strong>
                </div>

                <div>
                  <span>02 · PRACTICE</span>
                  <strong>
                    Complete adaptive questions on your weak areas
                  </strong>
                </div>

                <div>
                  <span>03 · REVIEW</span>
                  <strong>
                    Review incorrect answers and underlying concepts
                  </strong>
                </div>

                <div>
                  <span>04 · REASSESS</span>
                  <strong>
                    Measure your competency improvement
                  </strong>
                </div>

              </div>

              <button
                className="download-plan"
                onClick={downloadPlan}
              >
                Download My Learning Plan ↓
              </button>

            </div>

          )}

        </section>

        {/* ACTIONS */}

        <section className="analysis-actions">

          <button
            onClick={() => (window.location.href = '/quiz')}
          >
            Start Adaptive Learning →
          </button>

          <button
            onClick={() => (window.location.href = '/recommended')}
          >
            View Learning Recommendations →
          </button>

        </section>

      </section>

      <footer className="analysis-footer">

        <span>
          PAPERSCOPE — SMART INDIA HACKATHON 2026
        </span>

        <span>
          CONTACT US · contact@paperscope.in
        </span>

      </footer>

    </main>
  )
}

export default Analysis
