import { useState } from 'react'
import './Plan.css'

function Plan() {
  const [dailyTime, setDailyTime] = useState('')
  const [analysis, setAnalysis] = useState(() => {
    try {
      return JSON.parse(
        localStorage.getItem('paperscope_active_analysis') || 'null'
      )
    } catch {
      return null
    }
  })
  const [days, setDays] = useState('')
  const [preferredTime, setPreferredTime] = useState('')
  const [planGenerated, setPlanGenerated] = useState(false)

  const adaptive = analysis?.adaptive_learning || {}

  const priorities = adaptive?.topic_priorities || []

  const primaryPriority =
    adaptive?.focus_topic ||
    priorities[0]?.topic ||
    'Your highest-priority competency'

  const recommendedDifficulty =
    adaptive?.recommended_difficulty || 'medium'

  const learningMode =
    adaptive?.learning_mode || 'improvement'

  const generatePlan = () => {
    if (!dailyTime || !days || !preferredTime) return
    setPlanGenerated(true)
  }

  const downloadPlan = () => {
    const timeLabel =
      dailyTime === '30'
        ? '30 minutes'
        : dailyTime === '60'
        ? '1 hour'
        : dailyTime === '90'
        ? '1.5 hours'
        : dailyTime === '120'
        ? '2 hours'
        : '3+ hours'

    const preferenceLabel =
      preferredTime.charAt(0).toUpperCase() +
      preferredTime.slice(1)

    const plan = `
PAPERSCOPE
PERSONALIZED LEARNING PLAN
SMART INDIA HACKATHON 2026

========================================

LEARNING SCHEDULE

Daily Learning Time: ${timeLabel}
Days Per Week: ${days} days
Preferred Learning Time: ${preferenceLabel}

========================================

PRIMARY PRIORITY

${primaryPriority}

This priority is selected by PaperScope Adaptive Intelligence
from the learner's competency and assessment data.

Recommended difficulty: ${recommendedDifficulty}
Learning mode: ${learningMode}

========================================

RECOMMENDED DAILY PLAN

01 · 30 MIN
Learn ${primaryPriority}

02 · 20 MIN
Adaptive Questions · ${recommendedDifficulty}
Practice questions targeted to your highest-priority competency.

03 · 15 MIN
Review Incorrect Answers
Understand mistakes and reinforce weak concepts.

04 · 15 MIN
Complete Competency Reassessment
Measure whether your competency is improving.

========================================

PAPERSCOPE LEARNING INTELLIGENCE

Identify gaps.
Personalize learning.
Strengthen capability.

Generated by PaperScope AI
`

    const blob = new Blob([plan], {
      type: 'text/plain;charset=utf-8',
    })

    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')

    link.href = url
    link.download = 'PaperScope-Personalized-Learning-Plan.txt'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)

    URL.revokeObjectURL(url)
  }

  return (
    <main className="plan-page">

      <nav className="plan-nav">
        <button onClick={() => (window.location.href = '/dashboard')}>
          ← Dashboard
        </button>

        <strong>PaperScope</strong>

        <span>PERSONALIZED LEARNING PLAN</span>
      </nav>

      <section className="plan-container">

        <p className="section-label">
          PERSONALIZATION ENGINE
        </p>

        <h1>
          Build a plan that fits your life.
        </h1>

        <p className="plan-intro">
          Tell PaperScope when and how much you can learn.
          We'll prioritize your competency gaps around your available time.
        </p>

        <section className="plan-form">

          <label>
            <span>How much time can you learn each day?</span>

            <select
              value={dailyTime}
              onChange={(e) => setDailyTime(e.target.value)}
            >
              <option value="">Select</option>
              <option value="30">30 minutes</option>
              <option value="60">1 hour</option>
              <option value="90">1.5 hours</option>
              <option value="120">2 hours</option>
              <option value="180">3+ hours</option>
            </select>
          </label>

          <label>
            <span>How many days per week?</span>

            <select
              value={days}
              onChange={(e) => setDays(e.target.value)}
            >
              <option value="">Select</option>
              <option value="3">3 days</option>
              <option value="4">4 days</option>
              <option value="5">5 days</option>
              <option value="6">6 days</option>
              <option value="7">Every day</option>
            </select>
          </label>

          <label>
            <span>Preferred learning time</span>

            <select
              value={preferredTime}
              onChange={(e) => setPreferredTime(e.target.value)}
            >
              <option value="">Select</option>
              <option value="morning">Morning</option>
              <option value="afternoon">Afternoon</option>
              <option value="evening">Evening</option>
              <option value="night">Night</option>
              <option value="flexible">Flexible</option>
            </select>
          </label>

          <button
            className="generate-plan-button"
            onClick={generatePlan}
            disabled={!dailyTime || !days || !preferredTime}
          >
            Generate My Plan →
          </button>

        </section>

        {planGenerated && (
          <section className="generated-plan">

            <div className="generated-header">
              <div>
                <p className="section-label">
                  YOUR PERSONALIZED PLAN
                </p>

                <h2>
                  Your priority: {primaryPriority}
                </h2>
              </div>

              <button
                className="download-plan-button"
                onClick={downloadPlan}
              >
                ↓ Download My Plan
              </button>
            </div>

            <div className="plan-summary">

              <div>
                <span>DAILY TIME</span>
                <strong>
                  {dailyTime === '30'
                    ? '30 min'
                    : dailyTime === '60'
                    ? '1 hr'
                    : dailyTime === '90'
                    ? '1.5 hrs'
                    : dailyTime === '120'
                    ? '2 hrs'
                    : '3+ hrs'}
                </strong>
              </div>

              <div>
                <span>DAYS / WEEK</span>
                <strong>
                  {days === '7' ? 'Every day' : `${days} days`}
                </strong>
              </div>

              <div>
                <span>PREFERRED TIME</span>
                <strong>
                  {preferredTime.charAt(0).toUpperCase() +
                    preferredTime.slice(1)}
                </strong>
              </div>

            </div>

            <div className="plan-items">

              <div>
                <span>01 · 30 MIN</span>
                <strong>Learn {primaryPriority}</strong>
                <p>
                  Focus on the concepts connected to your highest-priority
                  competency gap.
                </p>
              </div>

              <div>
                <span>02 · 20 MIN</span>
                <strong>
                  Adaptive Questions · {recommendedDifficulty}
                </strong>
                <p>
                  Practice questions are adjusted according to your
                  adaptive difficulty recommendation.
                </p>
              </div>

              <div>
                <span>03 · 15 MIN</span>
                <strong>Review Incorrect Answers</strong>
                <p>Understand mistakes and reinforce weak concepts.</p>
              </div>

              <div>
                <span>04 · 15 MIN</span>
                <strong>Competency Reassessment</strong>
                <p>Measure whether your competency is improving.</p>
              </div>

            </div>

            <div className="plan-bottom-message">
              PaperScope continuously adapts this plan as your competency
              changes. Current learning mode: {learningMode}.
            </div>

          </section>
        )}

      </section>

    </main>
  )
}

export default Plan
